version: '3'
services:
  openvpn:
    build:
      dockerfile: openvpn/Dockerfile
    ports:
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    volumes:
      - /home/corentin/vpnaas/config/openvpn:/etc/openvpn
      - /dev/net/tun:/dev/net/tun
